// <auto-generated />
using System;
using ChatbotBuilderEngine.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatbotBuilderEngine.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Abstract.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Enum", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Enum");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Links.DataLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InputPortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OutputPortId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DataLink");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Links.FlowLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InputNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OutputNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FlowLink");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.InputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.ImageData>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("InputPort<ImageData>");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.InputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("InputPort<OptionData>");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.InputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.TextData>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("InputPort<TextData>");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.OutputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.ImageData>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("OutputPort<ImageData>");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.OutputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("OutputPort<OptionData>");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.OutputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.TextData>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("OutputPort<TextData>");
                });

            modelBuilder.Entity("ImageOutputPortInputPort", b =>
                {
                    b.Property<Guid>("OutputPortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InputPortId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OutputPortId", "InputPortId");

                    b.HasIndex("InputPortId");

                    b.ToTable("ImageOutputPortInputPort");
                });

            modelBuilder.Entity("OptionOutputPortInputPort", b =>
                {
                    b.Property<Guid>("OutputPortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InputPortId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OutputPortId", "InputPortId");

                    b.HasIndex("InputPortId");

                    b.ToTable("OptionOutputPortInputPort");
                });

            modelBuilder.Entity("TextOutputPortInputPort", b =>
                {
                    b.Property<Guid>("OutputPortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InputPortId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OutputPortId", "InputPortId");

                    b.HasIndex("InputPortId");

                    b.ToTable("TextOutputPortInputPort");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.StaticNode<ChatbotBuilderEngine.Domain.ValueObjects.Data.ImageData>", b =>
                {
                    b.HasBaseType("ChatbotBuilderEngine.Domain.Graphs.Abstract.Node");

                    b.ToTable("StaticNode<ImageData>");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.StaticNode<ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData>", b =>
                {
                    b.HasBaseType("ChatbotBuilderEngine.Domain.Graphs.Abstract.Node");

                    b.ToTable("StaticNode<OptionData>");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.StaticNode<ChatbotBuilderEngine.Domain.ValueObjects.Data.TextData>", b =>
                {
                    b.HasBaseType("ChatbotBuilderEngine.Domain.Graphs.Abstract.Node");

                    b.ToTable("StaticNode<TextData>");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.SwitchNode", b =>
                {
                    b.HasBaseType("ChatbotBuilderEngine.Domain.Graphs.Abstract.Node");

                    b.Property<string>("Bindings")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<Guid>("EnumId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("EnumId");

                    b.ToTable("SwitchNode");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Enum", b =>
                {
                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.InfoMeta", "Info", b1 =>
                        {
                            b1.Property<Guid>("EnumId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Identifier")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EnumId");

                            b1.ToTable("Enum");

                            b1.WithOwner()
                                .HasForeignKey("EnumId");
                        });

                    b.OwnsMany("ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData", "Options", b1 =>
                        {
                            b1.Property<Guid>("EnumId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.HasKey("EnumId", "Id");

                            b1.ToTable("Enum_Options");

                            b1.WithOwner()
                                .HasForeignKey("EnumId");
                        });

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Options");
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Links.DataLink", b =>
                {
                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.InfoMeta", "Info", b1 =>
                        {
                            b1.Property<Guid>("DataLinkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Identifier")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DataLinkId");

                            b1.ToTable("DataLink");

                            b1.WithOwner()
                                .HasForeignKey("DataLinkId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.VisualMeta", "Visual", b1 =>
                        {
                            b1.Property<Guid>("DataLinkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.HasKey("DataLinkId");

                            b1.ToTable("DataLink");

                            b1.WithOwner()
                                .HasForeignKey("DataLinkId");
                        });

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Visual")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Links.FlowLink", b =>
                {
                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.InfoMeta", "Info", b1 =>
                        {
                            b1.Property<Guid>("FlowLinkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Identifier")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FlowLinkId");

                            b1.ToTable("FlowLink");

                            b1.WithOwner()
                                .HasForeignKey("FlowLinkId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.VisualMeta", "Visual", b1 =>
                        {
                            b1.Property<Guid>("FlowLinkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.HasKey("FlowLinkId");

                            b1.ToTable("FlowLink");

                            b1.WithOwner()
                                .HasForeignKey("FlowLinkId");
                        });

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Visual")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.InputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.ImageData>", b =>
                {
                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Abstract.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ChatbotBuilderEngine.Domain.ValueObjects.Data.ImageData", "Data", b1 =>
                        {
                            b1.Property<Guid>("InputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InputPortId");

                            b1.ToTable("InputPort<ImageData>");

                            b1.WithOwner()
                                .HasForeignKey("InputPortId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.InfoMeta", "Info", b1 =>
                        {
                            b1.Property<Guid>("InputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Identifier")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InputPortId");

                            b1.ToTable("InputPort<ImageData>");

                            b1.WithOwner()
                                .HasForeignKey("InputPortId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.VisualMeta", "Visual", b1 =>
                        {
                            b1.Property<Guid>("InputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.HasKey("InputPortId");

                            b1.ToTable("InputPort<ImageData>");

                            b1.WithOwner()
                                .HasForeignKey("InputPortId");
                        });

                    b.Navigation("Data");

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Visual")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.InputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData>", b =>
                {
                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Abstract.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.SwitchNode", null)
                        .WithOne("InputPort")
                        .HasForeignKey("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.InputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData>", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData", "Data", b1 =>
                        {
                            b1.Property<Guid>("InputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("EnumId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InputPortId");

                            b1.ToTable("InputPort<OptionData>");

                            b1.WithOwner()
                                .HasForeignKey("InputPortId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.InfoMeta", "Info", b1 =>
                        {
                            b1.Property<Guid>("InputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Identifier")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InputPortId");

                            b1.ToTable("InputPort<OptionData>");

                            b1.WithOwner()
                                .HasForeignKey("InputPortId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.VisualMeta", "Visual", b1 =>
                        {
                            b1.Property<Guid>("InputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.HasKey("InputPortId");

                            b1.ToTable("InputPort<OptionData>");

                            b1.WithOwner()
                                .HasForeignKey("InputPortId");
                        });

                    b.Navigation("Data");

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Visual")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.InputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.TextData>", b =>
                {
                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Abstract.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ChatbotBuilderEngine.Domain.ValueObjects.Data.TextData", "Data", b1 =>
                        {
                            b1.Property<Guid>("InputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InputPortId");

                            b1.ToTable("InputPort<TextData>");

                            b1.WithOwner()
                                .HasForeignKey("InputPortId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.InfoMeta", "Info", b1 =>
                        {
                            b1.Property<Guid>("InputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Identifier")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InputPortId");

                            b1.ToTable("InputPort<TextData>");

                            b1.WithOwner()
                                .HasForeignKey("InputPortId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.VisualMeta", "Visual", b1 =>
                        {
                            b1.Property<Guid>("InputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.HasKey("InputPortId");

                            b1.ToTable("InputPort<TextData>");

                            b1.WithOwner()
                                .HasForeignKey("InputPortId");
                        });

                    b.Navigation("Data");

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Visual")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.OutputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.ImageData>", b =>
                {
                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Abstract.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.StaticNode<ChatbotBuilderEngine.Domain.ValueObjects.Data.ImageData>", null)
                        .WithOne("OutputPort")
                        .HasForeignKey("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.OutputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.ImageData>", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.InfoMeta", "Info", b1 =>
                        {
                            b1.Property<Guid>("OutputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Identifier")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OutputPortId");

                            b1.ToTable("OutputPort<ImageData>");

                            b1.WithOwner()
                                .HasForeignKey("OutputPortId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.VisualMeta", "Visual", b1 =>
                        {
                            b1.Property<Guid>("OutputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.HasKey("OutputPortId");

                            b1.ToTable("OutputPort<ImageData>");

                            b1.WithOwner()
                                .HasForeignKey("OutputPortId");
                        });

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Visual")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.OutputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData>", b =>
                {
                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Abstract.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.StaticNode<ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData>", null)
                        .WithOne("OutputPort")
                        .HasForeignKey("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.OutputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData>", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.InfoMeta", "Info", b1 =>
                        {
                            b1.Property<Guid>("OutputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Identifier")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OutputPortId");

                            b1.ToTable("OutputPort<OptionData>");

                            b1.WithOwner()
                                .HasForeignKey("OutputPortId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.VisualMeta", "Visual", b1 =>
                        {
                            b1.Property<Guid>("OutputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.HasKey("OutputPortId");

                            b1.ToTable("OutputPort<OptionData>");

                            b1.WithOwner()
                                .HasForeignKey("OutputPortId");
                        });

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Visual")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.OutputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.TextData>", b =>
                {
                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Abstract.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.StaticNode<ChatbotBuilderEngine.Domain.ValueObjects.Data.TextData>", null)
                        .WithOne("OutputPort")
                        .HasForeignKey("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.OutputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.TextData>", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.InfoMeta", "Info", b1 =>
                        {
                            b1.Property<Guid>("OutputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Identifier")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OutputPortId");

                            b1.ToTable("OutputPort<TextData>");

                            b1.WithOwner()
                                .HasForeignKey("OutputPortId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.VisualMeta", "Visual", b1 =>
                        {
                            b1.Property<Guid>("OutputPortId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.HasKey("OutputPortId");

                            b1.ToTable("OutputPort<TextData>");

                            b1.WithOwner()
                                .HasForeignKey("OutputPortId");
                        });

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Visual")
                        .IsRequired();
                });

            modelBuilder.Entity("ImageOutputPortInputPort", b =>
                {
                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.InputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.ImageData>", null)
                        .WithMany()
                        .HasForeignKey("InputPortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.OutputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.ImageData>", null)
                        .WithMany()
                        .HasForeignKey("OutputPortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptionOutputPortInputPort", b =>
                {
                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.InputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData>", null)
                        .WithMany()
                        .HasForeignKey("InputPortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.OutputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData>", null)
                        .WithMany()
                        .HasForeignKey("OutputPortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TextOutputPortInputPort", b =>
                {
                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.InputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.TextData>", null)
                        .WithMany()
                        .HasForeignKey("InputPortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Entities.Ports.OutputPort<ChatbotBuilderEngine.Domain.ValueObjects.Data.TextData>", null)
                        .WithMany()
                        .HasForeignKey("OutputPortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.StaticNode<ChatbotBuilderEngine.Domain.ValueObjects.Data.ImageData>", b =>
                {
                    b.OwnsOne("ChatbotBuilderEngine.Domain.ValueObjects.Data.ImageData", "Data", b1 =>
                        {
                            b1.Property<Guid>("StaticNodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StaticNodeId");

                            b1.ToTable("StaticNode<ImageData>");

                            b1.WithOwner()
                                .HasForeignKey("StaticNodeId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.InfoMeta", "Info", b1 =>
                        {
                            b1.Property<Guid>("StaticNodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Identifier")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StaticNodeId");

                            b1.ToTable("StaticNode<ImageData>");

                            b1.WithOwner()
                                .HasForeignKey("StaticNodeId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.VisualMeta", "Visual", b1 =>
                        {
                            b1.Property<Guid>("StaticNodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.HasKey("StaticNodeId");

                            b1.ToTable("StaticNode<ImageData>");

                            b1.WithOwner()
                                .HasForeignKey("StaticNodeId");
                        });

                    b.Navigation("Data");

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Visual")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.StaticNode<ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData>", b =>
                {
                    b.OwnsOne("ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData", "Data", b1 =>
                        {
                            b1.Property<Guid>("StaticNodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("EnumId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StaticNodeId");

                            b1.ToTable("StaticNode<OptionData>");

                            b1.WithOwner()
                                .HasForeignKey("StaticNodeId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.InfoMeta", "Info", b1 =>
                        {
                            b1.Property<Guid>("StaticNodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Identifier")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StaticNodeId");

                            b1.ToTable("StaticNode<OptionData>");

                            b1.WithOwner()
                                .HasForeignKey("StaticNodeId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.VisualMeta", "Visual", b1 =>
                        {
                            b1.Property<Guid>("StaticNodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.HasKey("StaticNodeId");

                            b1.ToTable("StaticNode<OptionData>");

                            b1.WithOwner()
                                .HasForeignKey("StaticNodeId");
                        });

                    b.Navigation("Data");

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Visual")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.StaticNode<ChatbotBuilderEngine.Domain.ValueObjects.Data.TextData>", b =>
                {
                    b.OwnsOne("ChatbotBuilderEngine.Domain.ValueObjects.Data.TextData", "Data", b1 =>
                        {
                            b1.Property<Guid>("StaticNodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StaticNodeId");

                            b1.ToTable("StaticNode<TextData>");

                            b1.WithOwner()
                                .HasForeignKey("StaticNodeId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.InfoMeta", "Info", b1 =>
                        {
                            b1.Property<Guid>("StaticNodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Identifier")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StaticNodeId");

                            b1.ToTable("StaticNode<TextData>");

                            b1.WithOwner()
                                .HasForeignKey("StaticNodeId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.VisualMeta", "Visual", b1 =>
                        {
                            b1.Property<Guid>("StaticNodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.HasKey("StaticNodeId");

                            b1.ToTable("StaticNode<TextData>");

                            b1.WithOwner()
                                .HasForeignKey("StaticNodeId");
                        });

                    b.Navigation("Data");

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Visual")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.SwitchNode", b =>
                {
                    b.HasOne("ChatbotBuilderEngine.Domain.Graphs.Entities.Enum", "Enum")
                        .WithMany()
                        .HasForeignKey("EnumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.InfoMeta", "Info", b1 =>
                        {
                            b1.Property<Guid>("SwitchNodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Identifier")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SwitchNodeId");

                            b1.ToTable("SwitchNode");

                            b1.WithOwner()
                                .HasForeignKey("SwitchNodeId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData", "SelectedOption", b1 =>
                        {
                            b1.Property<Guid>("SwitchNodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("EnumId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SwitchNodeId");

                            b1.ToTable("SwitchNode");

                            b1.WithOwner()
                                .HasForeignKey("SwitchNodeId");
                        });

                    b.OwnsOne("ChatbotBuilderEngine.Domain.Graphs.ValueObjects.Meta.VisualMeta", "Visual", b1 =>
                        {
                            b1.Property<Guid>("SwitchNodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.HasKey("SwitchNodeId");

                            b1.ToTable("SwitchNode");

                            b1.WithOwner()
                                .HasForeignKey("SwitchNodeId");
                        });

                    b.Navigation("Enum");

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("SelectedOption");

                    b.Navigation("Visual")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.StaticNode<ChatbotBuilderEngine.Domain.ValueObjects.Data.ImageData>", b =>
                {
                    b.Navigation("OutputPort")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.StaticNode<ChatbotBuilderEngine.Domain.ValueObjects.Data.OptionData>", b =>
                {
                    b.Navigation("OutputPort")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.StaticNode<ChatbotBuilderEngine.Domain.ValueObjects.Data.TextData>", b =>
                {
                    b.Navigation("OutputPort")
                        .IsRequired();
                });

            modelBuilder.Entity("ChatbotBuilderEngine.Domain.Graphs.Entities.Nodes.SwitchNode", b =>
                {
                    b.Navigation("InputPort")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
